import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Vishnu',
      email: 'vishnucool20001@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Vinesh',
      email: 'uservine@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Jordan FLex',
      slug: 'Jorden Flex',
      category: 'shoe',
      Image: '/images/shoe1.jpg',
      price: 2500,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 6,
      countInStock: 7,
      description: 'Best selling',
    },
    {
      name: 'Blaze Neo',
      slug: 'Blaze',
      category: 'shoe',
      Image: '/images/shoe2.jpg',
      price: 2340,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 5,
      description: 'Best selling',
    },
    {
      name: 'Strike-Blade',
      slug: 'Strike-Blade',
      category: 'shoe',
      Image: '/images/shoe3.jpg',
      price: 2190,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 4,
      countInStock: 9,
      description: 'Best selling',
    },
    {
      name: 'Comfy-Fit',
      slug: 'Comfy-Fit',
      category: 'sandles',
      Image: '/images/shoe4.jpg',
      price: 940,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 3,
      countInStock: 3,
      description: 'Best selling',
    },
    {
      name: 'Air Max',
      slug: 'Air Max',
      category: 'shoe',
      Image: '/images/shoe5.jpg',
      price: 2780,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
      description: 'Best selling',
    },
    {
      name: 'Sneak-Fit',
      slug: 'Sneak Fit',
      category: 'shoe',
      Image: '/images/shoe6.jpg',
      price: 2100,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 7,
      countInStock: 6,
      description: 'Best selling',
    },
  ],
};
export default data;
